# use for run multiple docker containers

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - rabbitmq


  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - mongo
    
  
  
    

volumes:
  mongo_data:

